secretGenerator:
- name: mysql-pass
  literals:
  - password=MYSQL_PASS
resources:
  - clusterrolebinding-default.yaml     
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  - wordpress-route.yaml
  - loadbalance-route.yaml
